---
title: "Homework 4"
output: html_document
---



```{r}
#a
a <-c(1,2, 3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)
#b
b <-c(20,19,28,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1)
#c
v= c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1)

# here we are using the function c() to assign v,b,a vector arguments and concentrating said arguments end to end
#d
dtp= c(4,6,3)
#e
rep(c(4,6,3), times=4) #here we are using the rep function along with the c function to return the vector (4,6,3) 4 times 
#f
dtp1=c(rep(c(dtp),times=6), rep(c(4),times=5), rep(c(3),times=4))
#g
dtp2=c(rep(c(dtp),times=10), rep(c(6),times=10), rep(c(3),times=20))



#2
x=c(seq(3,6,by=.1)) #here we are defining x as a vector whos arguments are a sequence starting at 3, ending at six and increasing by .1
z=exp(x)*cos(x) #then we create a vector z whos values are the exponential of x*cosx


#3

p=c(.1^3,.1^6,.1^9,.1^12,.1^15,.1^18,.1^21,.1^24,.1^27,.1^30,.1^33,.1^36) #here we are defining two vectors h and p which have increasing exponential values and then multiply them together
h=c(.2^1,.2^4,.2^7,.2^10,.2^13,.2^16,.2^19,.2^22,.2^25,.2^28,.2^31,.2^34)

g=(h*p)


n=c(seq(1,25,by=1))
# here we definine a vector n which has the intger values 1 through 25 (using the c and sequence function)
l=c((2^n)/n)
# and then define a function l which is equal to 2^n divided by n

#4
i=c(seq(1,100,by=1)) #here we use the c and sequence function to define a vector with integers 1 through 100
ff=(i^3+4*i) #then define ff to be the vector whos arguments are i^3+4*i 
sum(ff)#i then use the sum function to get the summation of said arguments

ii=c(seq(1,25,by=1))# here i use the same process as above, but with a different vector fff
fff=((2^ii)/ii)+(3^ii)/(ii^2)
sum(fff)


#5
#here I use the paste function to create character vectors "label" 1 through 30
pp=c(paste("label", 1:30, sep = " "))
jj=c(paste("fn", 1:30, sep = ""))


#6
set.seed(50) #here we creating two vectors of random integers from 0 to 999 with length 250
xVec<-sample(0:999,250,replace=T)
yVec<-sample(0:999,250,replace=T)

#a #i define two vectors, one as a sequence going from 2 to 250 (increasing by 1) and the other from 1 to 249 increasing by 1 and then define aa to equal the nth element of yvec- mth element of xvec
n=seq(2,250,by=1)
m=seq(1,249,by=1)
aa=c(yVec[n]-xVec[m])

#b #similarly, I use the same sequences to define aaa to be the vector of sin of the mth element of yvec/cos nth element of xvec
aaa=c(sin(yVec[m])/cos(xVec[n]))

#c
m=seq(1,248,by=1)
n=seq(2,249,by=1)
k=seq(3,250,by=1)
aaaa=c(xVec[m]+2*xVec[n]-xVec[k]) #in a similar fashion, we create 3 vectors whose arguments are just sequences of numbers (starting from 1 2 3 and ending at 248 249 and 250) and then use those three vectors to call on the specific elements of  xvec to apply elementary operations on them

#d
m=seq(2,250,by=1)
n=seq(1,249,by=1)
aaaaa=c((exp(-yVec[m]))/(yVec[n]+10)) #here i use the same process to the yvec except with a different set of operations (exponential and division) and now we are summing them using the sum function at the end
sum(aaaaa)

#7
#a
y600=which(yVec>600) #here I use the which function to identify the values of yvec that are greater than 600 (and set said values equal to y600)
yVec[y600] #i then print the values of yvec with the corresponding index numbers we received from who

#b
which(yVec > 600) #here i use the which function to return the indexes of all yvec elements that are greater than 600

#c
xVec[y600] #here i print the values of xvec with the indexes of yvec whose elements are greater than 600

#d
xmean=mean(xVec) #i define a variable called xmean and use the mean function to set it equal to the mean of xvec
n=seq(1,250,by=1)
A=c(abs(xVec[n]-xmean)^(1/2))#then using a newly created sequence, i define a to be a vector of the absolute value of the nth element of xvec subtracted from xmean taken to the 1/2


#e
max(xVec) #here i find the max of xvec and define to variables to equal the elements in yvec that are less than 200+max(xVec) and greater than max(xVec)-200 and then add the lengths of those two vectors 
y996=which(yVec>996)
Y776=which(yVec>776)
length(y996)+length(Y776)

#f #here i define xvecmod2 to be our xvec with modular 2 operation applied to it
xvecmod2=xVec %% 2
n=which(xvecmod2<1) # i then define n using the which function to be the elements of xvecmode2 that are less than 1 (or equivalently for our case, equal to 0). And then use the length function to get the number of elements in n
length(n)



#g

h=sort.list(yVec)

# I use the sort.list function to create a list of the indexes of yVec in assecending order and set that list equal to 'h'. I then apply the list h to get the corresponding values of xvec
xVec[h]




#h
n=seq(1,249,3) #here I define n to be a vector using the sequence function which starts at 1, ends at 249 and increses by 3 and apply it to yvec to pick out the indexed positions equaling n
yVec[n]




#8
i=seq(2,38,by=2) #here i define to sequences (one starting at 2 other at 3) ending at 38 and 39 and increasing by two and define a to equal a vector who has values of (1, and then i/n)
n=seq(3,39,by=2)
a=c(1,i/n)
b=cumprod(a) # i then use the cumprod function on a and set that to b before summing b
sum(b)
'''




'''


